framework:
    cache:
        default_redis_provider: '%env(resolve:REDIS_URL)%'
        app: cache.adapter.redis
        pools:
            my_redis_cache:
                adapter: cache.adapter.redis
                provider: "Redis"
